# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'Coverd' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coverd

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'ApiAI'

  target 'CoverdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoverdUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
